# Generated by Django 4.2.13 on 2024-06-30 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('limit_subgrupo_membro', models.IntegerField()),
                ('limit_subgrupo', models.IntegerField()),
                ('convite_link', models.URLField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField()),
                ('descricao', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.administrador')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='SubgrupoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.grupo')),
                ('subgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.subgrupo')),
            ],
        ),
        migrations.AddField(
            model_name='subgrupo',
            name='grupo',
            field=models.ManyToManyField(through='sources.SubgrupoGrupo', to='sources.grupo'),
        ),
        migrations.AddField(
            model_name='subgrupo',
            name='representante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.integrante'),
        ),
        migrations.CreateModel(
            name='Solicita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.integrante')),
                ('subgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.subgrupo')),
            ],
        ),
        migrations.CreateModel(
            name='IntegranteSubgrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.integrante')),
                ('subgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.subgrupo')),
            ],
        ),
        migrations.CreateModel(
            name='IntegranteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.grupo')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.integrante')),
            ],
        ),
        migrations.AddField(
            model_name='integrante',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sources.usuario'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.DateField()),
                ('participacao', models.TextField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arquivo', models.FileField(upload_to='avaliacoes/')),
                ('subgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.subgrupo')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.tarefa')),
            ],
        ),
        migrations.AddField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sources.usuario'),
        ),
    ]
